// Converter (dev-time): fetches ALL Ghostty theme files from the iTerm2-Color-Schemes
// corpus, parses them with the real src/theme.js parser, and emits vendored src/themes.js.
// The app never fetches at runtime — this bakes the data in. Re-run to update:
//   node test/make-themes.ts
//
// Source: https://github.com/mbadolato/iTerm2-Color-Schemes  (ghostty/ directory, MIT).
// Pinned to a specific commit for reproducibility — bump COMMIT to update the corpus.
import { writeFileSync } from 'node:fs';
import { parseTheme } from '../src/theme.js';

const COMMIT  = '982a5345c3ac4075320598100aa4155fdf8193fd';
const RAW     = `https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/${COMMIT}/ghostty/`;
const API     = `https://api.github.com/repos/mbadolato/iTerm2-Color-Schemes/contents/ghostty?ref=${COMMIT}`;
const DEFAULT = 'Catppuccin Mocha';

// 1. Directory listing.
process.stdout.write('fetching directory listing… ');
const dirRes = await fetch(API, { headers: { 'User-Agent': 'spicypath-make-themes' } });
if (!dirRes.ok) { console.error(`API ${dirRes.status}`); process.exit(1); }
const dir: { name: string; type: string }[] = await dirRes.json();
const files = dir.filter((f) => f.type === 'file').map((f) => f.name);
console.log(`${files.length} files`);

// 2. Fetch all in parallel batches of 24.
const BATCH = 24;
const out: Record<string, any> = {};
let ok = 0, fail = 0;
for (let i = 0; i < files.length; i += BATCH) {
  const chunk = files.slice(i, i + BATCH);
  process.stdout.write(`  [${i + 1}–${Math.min(i + BATCH, files.length)}/${files.length}] `);
  const results = await Promise.all(chunk.map(async (file) => {
    try {
      const res = await fetch(RAW + encodeURIComponent(file));
      if (!res.ok) return { file, err: `HTTP ${res.status}` };
      const th = parseTheme(await res.text(), file);
      if (!th) return { file, err: 'unparseable' };
      return { file, th };
    } catch (e: any) { return { file, err: e.message }; }
  }));
  for (const r of results) {
    if ('err' in r) { process.stdout.write(`✗`); fail++; }
    else { out[r.file] = r.th; process.stdout.write('.'); ok++; }
  }
  process.stdout.write('\n');
}
console.log(`\n${ok} ok, ${fail} failed`);
if (ok < 100) { console.error('FAIL: too few themes'); process.exit(1); }

// 3. Emit sorted, compact JS.
const body = Object.keys(out).sort().map((k) => {
  const t = out[k];
  const pal = '[' + t.palette.map((c: string) => `'${c}'`).join(', ') + ']';
  return `  ${JSON.stringify(k)}: { name: ${JSON.stringify(t.name)}, dark: ${t.dark}, ` +
    `bg: '${t.bg}', fg: '${t.fg}', cursor: '${t.cursor}', selection: '${t.selection}', palette: ${pal} },`;
}).join('\n');

const output = `// GENERATED by test/make-themes.ts — do not edit by hand.
// All Ghostty themes from mbadolato/iTerm2-Color-Schemes @ ${COMMIT.slice(0, 8)}.
// Regenerate: node test/make-themes.ts
export const THEMES_SOURCE = ${JSON.stringify(RAW)};
export const DEFAULT_THEME = ${JSON.stringify(DEFAULT)};
export const THEMES = {
${body}
};
`;
writeFileSync(new URL('../src/themes.js', import.meta.url), output);
console.log(`wrote src/themes.js — ${ok} themes, default "${DEFAULT}"`);
